### ISSUE TITLE
bug: readme component in fullHeight mode occupies at max 500px height

### ISSUE THREAD

**Issue by ikatlinsky** [AxisCommunications/backstage-plugins#110]
### Describe the bug

When using the readme component in fullHeight mode it takes at max of 500px height, while it should take all available height.

### To reproduce

Add readme card in a fullHeight mode

```jsx
<EntityLayout.Route path='/readme' title='Readme'>
      <ReadmeCard variant="fullHeight" />
    </EntityLayout.Route>
```

### Screenshots

![image](https://github.com/AxisCommunications/backstage-plugins/assets/1006457/e4465ef2-7ce2-4638-bd18-62d4a4f51097)

**Comment by fridajac** [comment]
Hi @ikatlinsky! Thank you for this issue. Please take a look at the comments in your PR to discuss more about this feature :+1:

**Comment by ikatlinsky** [comment]
> Hi @ikatlinsky! Thank you for this issue. Please take a look at the comments in your PR to discuss more about this feature 👍

sure, will gladly answer any comments
