### ISSUE TITLE
Getting a 401 using a Bearer Token

### ISSUE THREAD

**Issue by stevenmchaves** [AxisCommunications/backstage-plugins#121]
> **Please do not disclose security vulnerabilities as issues. See our [security policy](../../SECURITY.md) for responsible disclosures.**

### Describe the bug

I following the instructions about using a Bearer token and I am getting a 401 when I check the health:

```
 curl localhost:7007/api/jira-dashboard/health
{"error":{"name":"AuthenticationError","message":"Missing credentials","stack":"AuthenticationError: Missing credentials\n    at DefaultHttpAuthService.credentials (/mnt/c/Users/u1175114/Gitlab-tstenv/backstage_poc/backstage/node_modules/@backstage/backend-defaults/node_modules/@backstage/backend-app-api/src/services/implementations/httpAuth/httpAuthServiceFactory.ts:150:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"},"request":{"method":"GET","url":"/api/jira-dashboard/health"},"response":{"statusCode":401}} 
```
Using the same Bearer token calling directly to the Jira instance it works correctly:
```
schaves:~$ curl -H "Authorization: ${JIRA_BEARER_TOKEN}" https://XXXXXXXXX/rest/api/2/project/SDLC
{"expand":"description,lead,url,projectKeys","self":"https://XXXXXXXXX/rest/api/2/project/10200","id":"10200","key":"SDLC","description":"","lead":{"self":"https://XXXXXXXXX/rest/api/2/user?username=q831841","key":"q831841","name":"q831841","avatarUrls":{"48x48":"https://XXXXXXXXX/secure/useravatar?ownerId=q831841&avatarId=10500","24x24":"https://jira.rwts-.........
}
```

### To reproduce
```
 curl localhost:7007/api/jira-dashboard/health
{"error":{"name":"AuthenticationError","message":"Missing credentials","stack":"AuthenticationError: Missing credentials\n    at DefaultHttpAuthService.credentials (/mnt/c/Users/u1175114/Gitlab-tstenv/backstage_poc/backstage/node_modules/@backstage/backend-defaults/node_modules/@backstage/backend-app-api/src/services/implementations/httpAuth/httpAuthServiceFactory.ts:150:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"},"request":{"method":"GET","url":"/api/jira-dashboard/health"},"response":{"statusCode":401}} 
```
OR

![image](https://github.com/AxisCommunications/backstage-plugins/assets/52677425/8acf42b1-6d2c-43bc-a547-5708305c7400)

Please provide as much context as possible and describe the *reproduction steps* that someone else can follow to recreate the issue 

Here are the important details for the backend setup:
![image](https://github.com/AxisCommunications/backstage-plugins/assets/52677425/641d10e4-e17f-42e4-a408-e470e55c6d3c)
![image](https://github.com/AxisCommunications/backstage-plugins/assets/52677425/8afc926e-0799-4603-9388-25de9a398935)
![image](https://github.com/AxisCommunications/backstage-plugins/assets/52677425/3f0f1429-ed43-43a3-87eb-d710c07ecfbc)

**Comment by anicke** [comment]
Hi, which backstage version are you running? I think it's due to the auth changes in [v1.24.0](https://github.com/backstage/backstage/releases/tag/v1.24.0). We may need to update these plugins to support the new backend system on backstage +1.24.0.

**Comment by stevenmchaves** [comment]
I am using 1.26.0 but it occurred on 1.25.0 as well.

If I revert back to 1.24.0, will that resolve the issue? If so is there a `backstage_cli` command to do the revert.

**Comment by anicke** [comment]
We are actually just about to do the upgrade as well so I'll try to fix it as soon as possible.

**Comment by anicke** [comment]
To clarify the issue here...

Using curl directly on the Jira "health" API will not work in a +v1.24 Backstage that uses the new backend system. This is because it enforces authentication by default. The issue from the "Jira Dashboard" entity tab is probably due to the Jira plugin is not using the new auth system to authenticate towards the catalog API.

**Comment by stevenmchaves** [comment]
Well no real change. Direct call to JIRA instance good.

```
curl localhost:7007/api/jira-dashboard
{"error":{"name":"AuthenticationError","message":"Missing credentials","stack":"AuthenticationError: Missing credentials\n    at DefaultHttpAuthService.credentials (/mnt/c/Users/u1175114/Gitlab-tstenv/backstage_poc/backstage/node_modules/@backstage/backend-app-api/src/services/implementations/httpAuth/httpAuthServiceFactory.ts:150:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"},"request":{"method":"GET","url":"/api/jira-dashboard"},"response":{"statusCode":401}}
```

**Comment by stevenmchaves** [comment]
<img width="721" alt="image" src="https://github.com/AxisCommunications/backstage-plugins/assets/52677425/fb6b561a-a0f6-42be-8d10-e0da3c9619a3">

Again:
`curl -H "Authorization: ${JIRA_BEARER_TOKEN}" https://XXXXXXXXX/rest/api/2/project/SDLC`
works fine.

**Comment by MZerbe** [comment]
Have you set the `jiraDashboard.annotationPrefix` configuration to something like `jira`?

If so, you must adjust your component annotation:
```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    jira/project-key: "SDLC"
```

**Comment by stevenmchaves** [comment]
Yes

**Comment by fjudith** [comment]
Same issue here with ou without specifying the `jiraDashboard.annotationPrefix`

**Comment by mepperla** [comment]
i am having the same issue

**Comment by knewman23** [comment]
Seeing a 404 as well, I can do curl with `and` without the `--user` specified with successful responses

`backstage`: 1.26.4
`plugin-jira-dashboard-backend`: 2.0.0
`plugin-jira-dashboard`: 1.0.2
`plugin-jira-dashboard-common`: 1.0.1

**Comment by GLundh** [comment]
Does your baseUrl include the ending slash?

**Comment by knewman23** [comment]
Yes it does `https://xxx.atlassian.net/rest/api/latest/`

**Comment by GLundh** [comment]
Please try latest version. Should have a better error message in the log.

**Comment by knewman23** [comment]
Upgraded to `2.1.0`

Here is my `app-config` entry

```
jiraDashboard:
  token: -u xxx@xxx.com:token
  baseUrl: https://xxx.atlassian.net/rest/api/latest/
  userEmailSuffix: xxx.com
```

Seeing 

```
[1] 2024-05-14T14:52:44.144Z jira-dashboard error Could not find Jira project MF: Failed to get project info for project key MF with error: Request failed with status code 404: Not Found type=plugin
```


```
{
  "error": {
    "name": "Error",
    "message": "Request failed with status 404 Not Found, {\"error\":\"No Jira project found with key MF\"}"
  },
  "response": {
    "statusCode": 404
  }
}
```

**Comment by knewman23** [comment]
Opening the url in the browser gives me a full json response 

```
{
"expand": "description,lead,issueTypes,url,projectKeys,permissions,insight",
"self": "https://xxx.atlassian.net/rest/api/2/project/xxx",
"id": "xxx",
"key": "MF",
"description": "",
...
}
```

**Comment by GLundh** [comment]
> Upgraded to `2.1.0`
> 
> Here is my `app-config` entry
> 
> ```
> jiraDashboard:
>   token: -u xxx@xxx.com:token
>   baseUrl: https://xxx.atlassian.net/rest/api/latest/
>   userEmailSuffix: xxx.com
> ```

I'm not sure what's going on here, but that looks like a curl parameter for setting user and password.

Can you try 
```
  jiraDashboard:
    token: "Bearer <token>"
```
 where '<token>' is your token?

**Comment by knewman23** [comment]
The `Bearer <token>` format didn't work, but using `Basic <base64_token>` from the [docs](https://developer.atlassian.com/cloud/jira/platform/basic-auth-for-rest-apis/#supply-basic-auth-headers) did work!

**Comment by rishabh19sachan** [comment]
still facing same issue " 2024-06-22T13:52:34.505Z rootHttpRouter info ::1 - - [22/Jun/2024:13:52:34 +0000] "GET /api/jira-dashboard/health HTTP/1.1" 401 521 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" type=incomingRequest"

jiraDashboard:
  token: Bearer <>
  baseUrl: http://localhost:82/rest/api/2/
  userEmailSuffix: gmail.com
  annotationPrefix: jira

**Comment by GLundh** [comment]
@rishabh19sachan:  It looks like you are not authenticated against the Backstage backend. Are you using the new backend or the old one? Could you post all the code (censored where needed, of course) you used to setup the plugin?

**Comment by rishabh19sachan** [comment]
@GLundh its working now using new backend.
