### ISSUE TITLE
readme - 500 Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by piatkiewicz** [AxisCommunications/backstage-plugins#134]
I've set `readme` and `readme-backend` plugins like it's described [here](https://github.com/AxisCommunications/backstage-plugins/tree/main/plugins/readme#getting-started) and [here](https://github.com/AxisCommunications/backstage-plugins/blob/main/plugins/readme-backend/README.md#setup) (old backend) with no more changes in code and got this error

```
Cannot set headers after they are sent to the client\n    
at ServerResponse.setHeader (node:_http_outgoing:659:11)\n    
at ServerResponse.header (/app/node_modules/express/lib/response.js:795:10
at ServerResponse.send (/app/node_modules/express/lib/response.js:175:12)\n    
at ServerResponse.json (/app/node_modules/express/lib/response.js:279:15)\n    
at /app/node_modules/@axis-backstage/plugin-readme-backend/dist/index.cjs.js:123:26\n    
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","type":"errorHandler"} 
```

[Linguist](https://github.com/backstage/community-plugins/tree/main/workspaces/linguist) data was loaded fine, but readme failed
![image](https://github.com/AxisCommunications/backstage-plugins/assets/8793897/dfb6299c-30ce-4027-b1ce-679038fac34f)

Any ideas what could be the reason? I can try to provide more details

These messages are present in logs:
```
{"level":"info","message":"::ffff:my.ip - - [20/May/2024:14:32:38 +0000]Initializing readme backend \"GET /favicon.ico HTTP/1.1\" 200 - \"-\" \"mybrowserinfo\"","service":"backstage","type":"incomingRequest"}

{"level":"info","message":"Fetch README component:default/testrepo: https://github.com/myorgname/testrepo/README, text/plain ","plugin":"readme","service":"backstage","type":"plugin"}

{"level":"info","message":"Readme not found for component:default/testrepo","plugin":"readme","service":"backstage","type":"plugin"}
```
(I replaced ip with `my.ip`, browser info with `mybrowserinfo` and org, repo name with `myorgname` and `testrepo` above)

**Comment by fridajac** [comment]
Hi @piatkiewicz! Thank you for reporting this issue, I'll have a look at it!

**Comment by nia-potato** [comment]
hi @fridajac  when will this be released approximately?

**Comment by fridajac** [comment]
> hi @fridajac when will this be released approximately?

Hi! Thank you for reminding me, I fix :)
