### ISSUE TITLE
Feature - Show Jira priority in the Jira Table

### ISSUE THREAD

**Issue by mark-con** [AxisCommunications/backstage-plugins#140]
### Describe the feature

Currently the Jira table shows the Key, Summary, Status and Assignee.

It would be a nice enhancement to add the priority as a column in this table to allow users to quickly idenfiy the highest priority items of unassigned Jiras.

### Added value

This enhancement would allow me as a user to use the Jira dashboard more as a central point to view all tickets without having to navigate to Jira to see priority therefore allowing me to assign myself high priority tickets sooner.

**Comment by fridajac** [comment]
Hi @mark-con ! 

Thank your for your great suggestion. The Axis-Backstage team will discuss this at our next stand-up :+1: 

I'll get back to you as soon as I can!

**Comment by fridajac** [comment]
Hi again @mark-con!

I've discussed this feature with the team and it's a great idea. Let's add the Jira priority to the table! 

We look forward to an PR. Let us know if you don't have the possibility to implement this and we will add it to our backlog. :1st_place_medal:

**Comment by mark-con** [comment]
Hi @fridajac,

Thanks for taking on the suggestion.

I will begin working on a PR for this change this week.

Review coming soon 🤞 

Take care 😃
