### ISSUE TITLE
backend.add not working

### ISSUE THREAD

**Issue by piyush94** [AxisCommunications/backstage-plugins#161]
> **Please do not disclose security vulnerabilities as issues. See our [security policy](../../SECURITY.md) for responsible disclosures.**

import("/Backstage/POC_Backstage/node_modules/@axis-backstage/plugin-jira-dashboard-backend/dist/index")>' is not assignable to parameter of type 'BackendFeature | Promise<{ default: BackendFeature; }>'.
  Type 'Promise<typeof import("/Backstage/POC_Backstage/node_modules/@axis-backstage/plugin-jira-dashboard-backend/dist/index")>' is not assignable to type 'Promise<{ default: BackendFeature; }>'.
    Type 'typeof import("/Backstage/POC_Backstage/node_modules/@axis-backstage/plugin-jira-dashboard-backend/dist/index")' is not assignable to type '{ default: BackendFeature; }'.
      Types of property 'default' are incompatible.
        Type '() => BackendFeature' is not assignable to type 'BackendFeature'.

[7m68[0m backend.add(import('@axis-backstage/plugin-jira-dashboard-backend'));

package.json:

"@axis-backstage/plugin-jira-dashboard-backend": "^2.4.0"

**Comment by anicke** [comment]
I think we just need to bump the dependencies. Hopefully #160 should fix this.

**Comment by piyush94** [comment]
Yes, I suspect the same. I am waiting for the new NPM package to be released.

**Comment by anicke** [comment]
Packages for 1.30 has been published!

**Comment by piyush94** [comment]
I meant axis-backstage/plugin-jira-dashboard-backend package.

**Comment by piyush94** [comment]
Thanks! @anicke. It's working now.
