### ISSUE TITLE
Filtering for Jira Tables

### ISSUE THREAD

**Issue by Aaron-Wood-Eric** [AxisCommunications/backstage-plugins#163]
### Feature

The Jira Tables currently does not provide filtering functionality other than the filter search box which does not allow for easy filtering of priorities such as "A" "B" or "C".
I propose to allow users to filter by status and priority using the multi-select filters.

### Value

This enhancement would enable Jira dashboard users to more easily display tickets by priority or specific status. Currently, this can be challenging with filters that include a large number of tickets.

### Additional context
Backstage's Table Component does not currently display the title correctly with the filter, so this would require the title to be displayed on an infocard which wraps around the table.

**Comment by anicke** [comment]
Yes, sounds reasonable!

**Comment by fridajac** [comment]
Hi @Aaron-Wood-Eric!

Sounds like a good idea. Do you have the possibility of creating this PR, or would you like us to add it to our backlog? :)

**Comment by Aaron-Wood-Eric** [comment]
Hi @fridajac 

I am currently working on the PR and will have it ready ASAP :)
