### ISSUE TITLE
JIRA - SearchQuery - list user issues across projects

### ISSUE THREAD

**Issue by Vity01** [AxisCommunications/backstage-plugins#170]
### Describe the feature

Current existing JIRA plugins show only detail about the selected project/component. We would like to list issues assigned for current logged user at the homepage (for multiple projects).
I see some limitation with the existing source code. 
Sure we can implement our own plugin, but I think this one requires just minor changes to open existing code. 
**Backend plugin** -  existing `searchJira` function is not used in `router.ts`.  A new endpoint would be introduced. 
**Frontend plugin** - extending APIClient to be able to call this new endpoint, a new Card "MyCurrentIssues" component using this new API call. It can easily reuse JiraTable component (it should have columns attribute list configurable to remove assignee column for this case)

What do you think? We can discuss it on BS Discord, my nickname is Vity01 there. 
I can do a PR, but I need to hear some positive feedback so there  is a possibility the PR will merged. 

### Added value
More features in this plugin.

**Comment by anicke** [comment]
Sounds good, that should not be much work.

The new endpoint can be called "my-issues" or something similar. It takes the current user from "httpAuth.credentials" and uses the "getAssignedToMeFilter" function to create a jira query?

**Comment by Vity01** [comment]
Hello @anicke!
I was so keen to do it so I spent yesterday to work on it. This is how it looks like now:

![image](https://github.com/user-attachments/assets/5485fe97-f14b-41f5-82a0-08a691dbd132)

In the end I made it more general - to provide endpoint for any custom JQL. I also added more options into JiraTable so anyone can create custom report based on that.
 
I am also thinking to add a definition for @drodil 's  [Homepage plugin](https://github.com/backstage/backstage/blob/master/plugins/home/README.md). But I don't have this plugin enabled at the moment, so I will leave it for now. 

I am currently cleaning and tuning code, then I will prepare PR. Be ready, it's not so small as I expected before. :-)

**Comment by anicke** [comment]
It's a bit problematic having an endpoint that accepts any JQL. We have intentionally made it so that it should only be possible to get any Jira information for projects that have opted in with the Jira annotation. There can be orgs that have specific users that have access to Backstage but not Jira. Some orgs can have sensitive information in Jira not suitable for the complete organisation.

**Comment by Vity01** [comment]
ok, I will rework it.
