### ISSUE TITLE
ReadmeCard component height

### ISSUE THREAD

**Issue by dimapasko** [AxisCommunications/backstage-plugins#174]
### Describe the feature

At present, configuring the height of the `ReadmeCard` is not supported. 

According to [this code](https://github.com/AxisCommunications/backstage-plugins/blob/5a933c34eacedb35e940ec5ff10a73254ea1b523/plugins/readme/src/components/ReadmeCard/ReadmeCard.tsx#L21), the height can only be set to either `235px` (which may be too small) or `full screen` (which requires a specific layout). 

Could the option to adjust the component height be added?
 
### Added value

`ReadmeCard` will be more customizable and adaptable to various layouts.

### Additional context

Here is an example of how it appears in our situation.

<img width="2296" alt="image" src="https://github.com/user-attachments/assets/2e0cac81-930a-426c-9f1b-5ae62e466256">

**Comment by anicke** [comment]
Yes, this should be possible to adjust.

**Comment by fridajac** [comment]
Solved by https://github.com/AxisCommunications/backstage-plugins/pull/195? 😊

**Comment by dimapasko** [comment]
This is excellent news and exactly what I require. 
Could you please publish the new release?

**Comment by fridajac** [comment]
@dimapasko They are published to npm, so you should be able to run yarn backstage-cli versions:bump --pattern "@axis-backstage/*" in you repository to get this feature?
