### ISSUE TITLE
Jira Table Link Titles

### ISSUE THREAD

**Issue by Aaron-Wood-Eric** [AxisCommunications/backstage-plugins#177]
### Feature
Update the title component to a link which points to the query used to form the table.
`<Link to={'${getJiraUrl(project)}issues/?jql=${tableContent.query}'}>`
![image](https://github.com/user-attachments/assets/748ea12f-5af2-4d9f-bd46-e8890c6a1f9b)

### Value
Jira Dashboard users would have easy access to the filter within JIRA.

### Context
Current the searchJira, getIssuesByComponent.. functions in [api.ts](https://github.com/AxisCommunications/backstage-plugins/blob/5a933c34eacedb35e940ec5ff10a73254ea1b523/plugins/jira-dashboard-backend/src/api.ts) all return response.issues rather than the full response object which contains the JQL query. The return value will need to be changed to include the query.

**Comment by fridajac** [comment]
Great idea! Feel free to add a PR and we will have a look :) Thank you for the suggestion!

**Comment by Aaron-Wood-Eric** [comment]
This Issue seems to be partially covered by PR #127 as it updates the needed fields in the api.ts I can create the PR once this has been resolved.
