### ISSUE TITLE
Multiple Jira instances

### ISSUE THREAD

**Issue by grantila** [AxisCommunications/backstage-plugins#198]
### Describe the feature

We're looking into using this Jira plugin, but need to be able to have multiple Jira instances, like some other plugins are capable of (e.g. the [SonarQube plugin](https://github.com/backstage/community-plugins/blob/main/workspaces/sonarqube/plugins/sonarqube-backend/README.md#example---multiple-global-instance)) and similar to integrations where you can have multiple GitHub, GitLab instances.

Do you have any plans to support this, and if not, would you be positive to a contribution to this plugin to support this?

**Comment by anicke** [comment]
We don't have a plan to implement this but we are open for contributions. We could use a similar annotation and config as the SonarQube examples?

**Comment by grantila** [comment]
Yeah, that would make sense for simplicity, to keep the multi-instance interface aligned. I'll look into this and prepare a PR.
