### ISSUE TITLE
Issue with Jira-dashboard plugin

### ISSUE THREAD

**Issue by reynierpupo-tomtom** [AxisCommunications/backstage-plugins#200]
> **Please do not disclose security vulnerabilities as issues. See our [security policy](../../SECURITY.md) for responsible disclosures.**

### Describe the bug

I have configured everything described in the readme file. Now trying to render the logged in user tasks but I get an error from the backend plugin 
<img width="1458" alt="image" src="https://github.com/user-attachments/assets/0862725e-220b-4a0a-b3bb-30e2b3cd982a">

### To reproduce

Please provide as much context as possible and describe the *reproduction steps* that someone else can follow to recreate the issue on their own.

A team member will try to reproduce the issue with your provided steps. If there are no reproduction steps or no obvious way to reproduce the issue, the team will ask you for those steps. Bugs without steps will not be addressed until they can be reproduced.

1. Set up '...'
2. Do this '...'
3. See error

### Environment

- Axis device model: [e.g. Q1615 Mk III]
- Axis device firmware version: [e.g. 10.5]
- Stack trace or logs: [e.g. Axis device system logs]
- OS and version: [e.g. macOS v12.2.1, Ubuntu 20.04 LTS, Windows build 21996.1]
- Version: [version of the application, SDK, runtime environment, package manager, interpreter, compiler, depending on what seems relevant]

**Comment by anicke** [comment]
Some questions:
* Which backstage version?
* Are you using the old or the new backend? 
* If the old backend, how does the "createPlugin" setup look like?

**Comment by anicke** [comment]
I just realised that the instruction for the old backend system is incorrect. The "createRouter" function also needs the
"coreServices.userInfo" as an argument.

   ```ts
   import { createRouter } from '@axis-backstage/plugin-jira-dashboard-backend';
   import { Router } from 'express';
   import { PluginEnvironment } from '../types';

   export default async function createPlugin(
     env: PluginEnvironment,
   ): Promise<Router> {
     return await createRouter({
       logger: env.logger,
       config: env.config,
       discovery: env.discovery,
       identity: env.identity,
       tokenManager: env.tokenManager,
       **userInfo: coreServices.userInfo**     // Is this available in the old "PluginEnvironment"?
     });
   }
   ```

**Comment by reynierpupo-tomtom** [comment]
> I just realised that the instruction for the old backend system is incorrect. The "createRouter" function also needs the "coreServices.userInfo" as an argument.
> 
> ```ts
> import { createRouter } from '@axis-backstage/plugin-jira-dashboard-backend';
> import { Router } from 'express';
> import { PluginEnvironment } from '../types';
> 
> export default async function createPlugin(
>   env: PluginEnvironment,
> ): Promise<Router> {
>   return await createRouter({
>     logger: env.logger,
>     config: env.config,
>     discovery: env.discovery,
>     identity: env.identity,
>     tokenManager: env.tokenManager,
>     **userInfo: coreServices.userInfo**     // Is this available in the old "PluginEnvironment"?
>   });
> }
> ```

Thanks @anicke , It's available, will try to provide it also.

**Comment by fridajac** [comment]
Can I close this issue @reynierpupo-tomtom?
