### ISSUE TITLE
Support for user defined additional filters

### ISSUE THREAD

**Issue by SaachiNayyer** [AxisCommunications/backstage-plugins#210]
### Describe the feature
This enhancement will allow user to add any additional filters in app-config other than these current default filters [openFilter, incomingFilter, assigneeToMeFilter].
for example 
defaultFilters:
    - name: 'Open Bugs'
      shortName: 'Bugs'
      query: 'type = bug AND resolution = Unresolved ORDER BY updated DESC, priority DESC'
    - name: 'Epics'
      shortName: 'Epics'
      query: 'type = epic AND resolution = Unresolved ORDER BY updated DESC, priority DESC'

### Added value

 This provides flexibility for users to tailor their dashboard views without modifying the core codebase.

### Additional context

![image](https://github.com/user-attachments/assets/5227e2fd-18a6-41b2-a5c7-a5b13f8a63e7)

**Comment by anicke** [comment]
Hi, this sounds like a very useful feature! A PR would be much appreciated.
