### ISSUE TITLE
Jira-Dashboard: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by goalie-lisa** [AxisCommunications/backstage-plugins#212]
### Describe the bug

When visiting the jira-dashboard tab the following error occurs and nothing ist shown except for an error message with the stacktrace. Authentication with Jira works fine.

### Stacktrace

Uncaught TypeError: Cannot read properties of undefined (reading 'map')
    at transformAssignees (lib.esm.js:27:17)
    at JiraTable (JiraTable.esm.js:40:66)
    at renderWithHooks (react-dom.development.js:15486:18)
    at mountIndeterminateComponent (react-dom.development.js:20098:13)
    at beginWork (react-dom.development.js:21621:16)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27485:7)
    at performUnitOfWork (react-dom.development.js:26591:12)

### To reproduce

Set up Jira Dashboard Plugin as shown in the Readme. Then visit the Jira Dashboard Tab of an entity.

### Environment

 app@0.0.0 
│ ├── @axis-backstage/plugin-jira-dashboard@1.13.1
│ ├── @axis-backstage/plugin-readme@0.12.0
│ ├── @backstage-community/plugin-github-actions@0.6.24
│ ├── @backstage-community/plugin-jenkins@0.9.10
│ ├── @backstage-community/plugin-sentry@0.5.22
│ ├── @backstage-community/plugin-sonarqube@0.8.7
│ ├── @backstage-community/plugin-tech-radar@0.7.11
│ ├── @backstage/app-defaults@1.5.13
│ ├── @backstage/catalog-model@1.7.1 deduped
│ ├── @backstage/cli@0.29.0 deduped
│ ├── @backstage/core-app-api@1.15.2 deduped
│ ├── @backstage/core-components@0.16.0 deduped
│ ├── @backstage/core-plugin-api@1.10.1 deduped
│ ├── @backstage/integration-react@1.2.1
│ ├── @backstage/plugin-api-docs@0.12.0
│ ├── @backstage/plugin-catalog-common@1.1.1
│ ├── @backstage/plugin-catalog-graph@0.4.12
│ ├── @backstage/plugin-catalog-import@0.12.6
│ ├── @backstage/plugin-catalog-react@1.14.1 deduped
│ ├── @backstage/plugin-catalog@1.25.0
│ ├── @backstage/plugin-devtools@0.1.20
│ ├── @backstage/plugin-home@0.8.1
│ ├── @backstage/plugin-org@0.6.32
│ ├── @backstage/plugin-permission-react@0.4.28
│ ├── @backstage/plugin-scaffolder@1.27.0
│ ├── @backstage/plugin-search-react@1.8.2
│ ├── @backstage/plugin-search@1.4.19
│ ├── @backstage/plugin-techdocs-module-addons-contrib@1.1.17
│ ├── @backstage/plugin-techdocs-react@1.2.10
│ ├── @backstage/plugin-techdocs@1.11.1
│ ├── @backstage/plugin-user-settings@0.8.15
│ ├── @backstage/theme@0.6.1 deduped
│ ├── @material-ui/core@4.12.4 deduped
│ ├── @material-ui/icons@4.11.3 deduped
│ ├── @roadiehq/backstage-plugin-jira@2.8.0
│ ├── @trimm/plugin-dependencytrack@0.3.1
│ ├── history@5.3.0
│ ├── react-dom@18.3.1
│ ├── react-router-dom@6.28.0
│ ├── react-router@6.28.0
│ ├── react-use@17.5.1 deduped
│ └── react@18.3.1 deduped
├─┬ backend@0.0.0 -> ./packages/backend
│ ├── @axis-backstage/plugin-jira-dashboard-backend@4.0.1
│ ├── @axis-backstage/plugin-readme-backend@0.10.1
│ ├── @backstage-community/plugin-jenkins-backend@0.4.12
│ ├── @backstage-community/plugin-sonarqube-backend@0.2.25
│ ├── @backstage/backend-common@0.25.0 deduped
│ ├── @backstage/backend-defaults@0.5.3 deduped
│ ├── @backstage/backend-plugin-api@1.0.2 deduped
│ ├── @backstage/backend-tasks@0.6.1
│ ├── @backstage/catalog-model@1.7.1 deduped
│ ├── @backstage/cli@0.29.0 deduped
│ ├── @backstage/config@1.3.0 deduped
│ ├── @backstage/plugin-app-backend@0.4.0
│ ├── @backstage/plugin-auth-backend-module-github-provider@0.2.2
│ ├── @backstage/plugin-auth-backend-module-guest-provider@0.2.2 deduped
│ ├── @backstage/plugin-auth-backend-module-oauth2-provider@0.3.2
│ ├── @backstage/plugin-auth-backend-module-oidc-provider@0.3.2
│ ├── @backstage/plugin-auth-backend@0.24.0 deduped
│ ├── @backstage/plugin-auth-node@0.5.4
│ ├── @backstage/plugin-catalog-backend-module-bitbucket-server@0.2.4
│ ├── @backstage/plugin-catalog-backend-module-ldap@0.10.0
│ ├── @backstage/plugin-catalog-backend-module-logs@0.1.4
│ ├── @backstage/plugin-catalog-backend-module-scaffolder-entity-model@0.2.2
│ ├── @backstage/plugin-catalog-backend@1.28.0
│ ├── @backstage/plugin-catalog-node@1.14.0
│ ├── @backstage/plugin-devtools-backend@0.4.2
│ ├── @backstage/plugin-events-backend@0.3.16
│ ├── @backstage/plugin-permission-backend-module-allow-all-policy@0.2.2
│ ├── @backstage/plugin-permission-backend@0.5.51
│ ├── @backstage/plugin-permission-common@0.8.2
│ ├── @backstage/plugin-permission-node@0.8.5
│ ├── @backstage/plugin-proxy-backend@0.5.8
│ ├── @backstage/plugin-scaffolder-backend-module-bitbucket-server@0.2.2
│ ├── @backstage/plugin-scaffolder-backend@1.27.0
│ ├── @backstage/plugin-search-backend-module-catalog@0.2.5
│ ├── @backstage/plugin-search-backend-module-pg@0.5.38
│ ├── @backstage/plugin-search-backend-module-techdocs@0.3.2
│ ├── @backstage/plugin-search-backend-node@1.3.5
│ ├── @backstage/plugin-search-backend@1.7.0
│ ├── @backstage/plugin-techdocs-backend@1.11.2
│ ├── @types/dockerode@3.3.32
│ ├── @types/express-serve-static-core@4.19.6
│ ├── @types/express@4.17.21
│ ├── @types/global-agent@2.1.3
│ ├── @types/luxon@2.4.0
│ ├── better-sqlite3@9.6.0
│ ├── dockerode@3.3.5
│ ├── node-gyp@9.4.1 deduped
│ ├── pg@8.13.1
│ └── winston@3.17.0

### Stacktrace

Uncaught TypeError: Cannot read properties of undefined (reading 'map')
    at transformAssignees (lib.esm.js:27:17)
    at JiraTable (JiraTable.esm.js:40:66)
    at renderWithHooks (react-dom.development.js:15486:18)
    at mountIndeterminateComponent (react-dom.development.js:20098:13)
    at beginWork (react-dom.development.js:21621:16)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27485:7)
    at performUnitOfWork (react-dom.development.js:26591:12)

Thanks for your help.

**Comment by gePower** [comment]
I am experiencing the same problem. The problem occurs when tableContent.issues in JiraTable.tsx (L55) are not defined.

**Comment by anicke** [comment]
1.13.2 has been published, please check if it works now.

**Comment by goalie-lisa** [comment]
Besides I don't understand why issues is here undefinded, because the backend serves the project and issue information correctly, when looking at the network traffic.

**Comment by gePower** [comment]
Thanks @anicke :) 

I don't see your change in npm.
![image](https://github.com/user-attachments/assets/bbded3e2-38d4-45b3-b4fa-86d1086aa0a4)

**Comment by goalie-lisa** [comment]
Thank you very much for your help. Now it works!
