### ISSUE TITLE
Release roadmap?

### ISSUE THREAD

**Issue by Zigu** [AxisCommunications/backstage-plugins#26]
Hi, 

sorry to misuse the issue function but I want to ask how your release roadmap looks like? I saw your comments on backstage Discord a while ago and have been waiting to integrate/test your plugin from an npm registry.

Thx.

**Comment by fridajac** [comment]
> Hi,
> 
> sorry to misuse the issue function but I want to ask how your release roadmap looks like? I saw your comments on backstage Discord a while ago and have been waiting to integrate/test your plugin from an npm registry.
> 
> Thx.

Hi Zugu! Nice to hear that you want to use our plugin. We are on our way, I hope to publish at the end of this day :)

**Comment by fridajac** [comment]
Hi again Zigu! It's published now! Let us know if you have any questions :+1:
