### ISSUE TITLE
Provide compatibility for the jira annotation with respective to roadie.io.

### ISSUE THREAD

**Issue by riginoommen** [AxisCommunications/backstage-plugins#48]
```
jira/project-key: KEY
jira/component:Component
```

This helps the users to adopt the plugin with less efforts

**Comment by riginoommen** [comment]
I really want to use this if i want to migrate to this plugin i have to perform certain migrations in terms of annotations. It will be great a provision is here

**Comment by fridajac** [comment]
Hi @riginoommen! We will discuss this within our team. It would be possible to make the annotation configurable, then everyone can choose the one that suits them best  :) We will get back to you shortly

**Comment by Vity01** [comment]
I came here to ask the same. @riginoommen is right. Please make it compatible. There are tons of existing catalog files using Roadies' definition.

**Comment by riginoommen** [comment]
I found one more issue in roadie its ```jira/component``` for component here its components

**Comment by fridajac** [comment]
@riginoommen True! We will have a look at it :+1:
