### ISSUE TITLE
README.md not picked up

### ISSUE THREAD

**Issue by christoph-buente** [AxisCommunications/backstage-plugins#60]
> **Please do not disclose security vulnerabilities as issues. See our [security policy](../../SECURITY.md) for responsible disclosures.**

### Describe the bug

We have installed the readme plugin. The README panel shows up on the detail page of a service. However, the standard text is shown, not the actual readme. I have read the trouble shooting guide, which indicated to change the `backstage.io/source-location` label to point to the `blob` path instead of the `tree` path. However, that would require us to do that for all the hundred services.

### To reproduce

Just install the plugin as is, define a component and see the default README card on the default page

1. Set up the readme plugin v.
2. Add a simple component using a catalog-info.yaml file hosted on github without specifying the `backstage.io/source-location` label
3. Import that file into backstage
4. Check the detail page of the component

### Environment

- latest backstage readme plugin version

### Additional context

My understanding that the label `backstage.io/source-location` is populated by backstage by default like this: `url:https://github.com/organisation-name/repository-name/tree/master/` but it should be `url:https://github.com/organisation-name/repository-name/blob/master/`

Instead of overriding the label, wouldn't it be easier, if the plugin modified the URL to the correct point? Thanks for your help, really appreciate it!

**Comment by fridajac** [comment]
@christoph-buente Thank you for submitting this issue! We will have a look at it a soon as we can :+1:

**Comment by fridajac** [comment]
Hi again @christoph-buente! We need some addition info the be able to handle this issue. 

By the "standard text", do you mean the erorr message:  "No README.md file found at source location?"

I had a look at it, and the url repository-name/tree/master should redirect to the correct repository-name/blob/master path by default. See https://github.com/backstage/backstage/blob/master/packages/integration/src/github/GithubIntegration.ts#L59C3-L59C13. It works for us in our GitHub repositories. Are you sure that your README file is located in the root of the project?

**Comment by christoph-buente** [comment]
Hi @fridajac,

thanks for looking into it. The `catalog-info.yaml` as well as the `README.md` files are located in the root of the github repository. 

With the default panel, i mean the one with the message: `No README.md file found at source location: https://github.com/org/repo/tree/master/`

Even though, the file is right there. And indeed, there is a redirect from `/tree/master` to `/blob/master/` when i call the URL in a browser. However, the backend does not seem to be able to pick it up.

<img width="618" alt="Untitled" src="https://github.com/AxisCommunications/backstage-plugins/assets/36998/0d51044d-1878-4029-bdec-c2892ac4f37f">

**Comment by MartinWallgren** [comment]
We are unable to reproduce this, there is not much we can do about this.
Could you contribute a suggested solution?

**Comment by piatkiewicz** [comment]
I have similar issue. Registering different repos from ADO, private and public from GitHub, but getting "NO README.md file found..." every time. Backstage on it's own fetches data from catalog-info.yaml correctly.
![image](https://github.com/AxisCommunications/backstage-plugins/assets/8793897/b840e370-b154-4de5-b026-c5c32a489690)

**Comment by supersol** [comment]
I think this is due to missing `readme-backend` part. There is a small note in the documentation that it also needs to be installed :)

**Comment by MartinWallgren** [comment]
> I think this is due to missing `readme-backend` part. There is a small note in the documentation that it also needs to be installed :)

Can anyone confirm that this is the root cause?
If it is, we could make it more obvious that the backend-plugin is missing from the installation.

**Comment by christoph-buente** [comment]
Hey, yes I can confirm it was the missing backend plugin. @supersol installed the backend plugin and now it works flawlessly. Sorry for the panic and for not following the documentation 100%. Thanks, @fridajac and @MartinWallgren for looking into it.

**Comment by fridajac** [comment]
> Hey, yes I can confirm it was the missing backend plugin. @supersol installed the backend plugin and now it works flawlessly. Sorry for the panic and for not following the documentation 100%. Thanks, @fridajac and @MartinWallgren for looking into it.

No problem, I'm just glad you want to use our plugin! :+1: I'll see if I can update the documentation so it's a little bit easier to catch this.

**Comment by piatkiewicz** [comment]
I have readme-backend in place following the guideline, but readme content is not showing up. Any advice how to debug it?

**Comment by bn1404** [comment]
> I have readme-backend in place following the guideline, but readme content is not showing up. Any advice how to debug it?

I also set up both plugins according to the guideline and it was not showing the content. Then; I fixed it by adding "/" to the end of the `backstage.io/source-location` value.

Old value: https://bitbucket.org/org-name/repo-id/src/master
New value: https://bitbucket.org/org-name/repo-id/src/master/
