### ISSUE TITLE
annotationPrefix is not working

### ISSUE THREAD

**Issue by yoramshai** [AxisCommunications/backstage-plugins#73]
### Describe the bug
annotationPrefix is ignored after adding `if={entity => isJiraDashboardAvailable(entity, 'jira')}` and added the environment variable 
 `JIRA_ANNOTATION_PREFIX` as "jira" as well.

Explain the behavior you would expect and the actual behavior.
I was expecting the code will avoid looking for "jira.com" prefix.

### To reproduce
set the changes I set above.

**Comment by yoramshai** [comment]
after removing the question mark it started to work 
![image](https://github.com/AxisCommunications/backstage-plugins/assets/11707803/7b101994-bd23-4908-9465-2e1c9af51543)

**Comment by fridajac** [comment]
I fix! :+1:
