### ISSUE TITLE
Unable to load StatusPage Integration

### ISSUE THREAD

**Issue by mattSSB** [AxisCommunications/backstage-plugins#85]
> **Please do not disclose security vulnerabilities as issues. See our [security policy](../../SECURITY.md) for responsible disclosures.**

### Describe the bug

Hi all, 

I have installed the Frontend and Backend integration and given the data from my StatusPage account but I am experiencing an issue attempting to see the data. 

The error is `No implementation available for apiRef{plugin.statuspage}`. I have provided a screenshot below. 

This issue is occurring in my current implementation of Backstage as well a fresh instance from the [Getting Started Documentation](https://backstage.io/docs/getting-started/)

### To reproduce

1. Create a new instance of Backstage using the [Getting Started Documentation](https://backstage.io/docs/getting-started/)
2. Install [StatusPage frontend ](https://github.com/AxisCommunications/backstage-plugins/blob/main/plugins/statuspage/README.md) and [StatusPage backend](https://github.com/AxisCommunications/backstage-plugins/tree/main/plugins/statuspage-backend)
3. Add annotations to a component
4. Navigate to where the Card is on the Component 
5. See error

### Screenshots

Error:
![image](https://github.com/AxisCommunications/backstage-plugins/assets/157729901/9f5d7e8f-294c-49df-9e9d-0b8f87069d65)

### Environment

- Stack trace or logs: Provided in screenshot above
- OS and version: Linux 6.6.12-linuxkit - linux/arm64
- Backstage Version: 1.23.3
- NodeJS Version: v18.19.1

### Additional context
I did make some small changes based on the plugin guides. They are:
1. Removed `authMiddleware`, changing `apiRouter.use('/statuspage', authMiddleware, await statuspage(statuspageEnv));` to simply `apiRouter.use('/statuspage', await statuspage(statuspageEnv));`. Adding it back in did not solve my issue
2. Changed `StatuspageEntityComponent` to `StatuspageEntityCard`, changing  `import { StatuspageEntityComponent, isStatuspageAvailable }` to `import { StatuspageEntityCart, isStatuspageAvailable }`

My config values are:
1. My statuspage configuration looks like the following:
![image](https://github.com/AxisCommunications/backstage-plugins/assets/157729901/5e75e7c2-dadb-4351-b36d-edd38e9fffe9)
2. My annotations look like the following:
![image](https://github.com/AxisCommunications/backstage-plugins/assets/157729901/46a1c409-e591-4b8f-aa44-d29e83b84e44)

**Comment by mattSSB** [comment]
Thank you for the response, that did solve the issues I was receiving. Appreciate it!

**Comment by GLundh** [comment]
Ok. The correct way to fix this is to setup an ApiFactory. Checkout this PR:

https://github.com/AxisCommunications/backstage-plugins/pull/87
