### ISSUE TITLE
Broken JIRA links when using Jira Server with additional PATH in JIRA Base URL

### ISSUE THREAD

**Issue by bernhardwacker** [AxisCommunications/backstage-plugins#88]
### Describe the bug

The Dashboard get's the Issues from a Jira Server instance with a BaseURL (https://SERVER/PATH/...) The Dashboard Frontend rewrites the URL into https://SERVER/... Ignoring the PATH part of the Jira BaseURL.

This results in JIRA Issues, which are displayed in the frontend with details, but the Links to JIRA are broken (missing the PATH). Therefore one cannot open them on the JIRA Server.

It looks as if the problem is in https://github.com/AxisCommunications/backstage-plugins/blob/main/plugins/jira-dashboard/src/lib.ts

````java
export const getProjectUrl = (project: Project) => {
  const url = new URL(project.self);
  return `https://${url.host}/browse/${project.key}`;
};
````

This function returns only the Host part of the URL, ignoring the additional PATH.

Example: 
Given: "self": "https://SERVER/PATH/rest/api/2/project/ID"

Actual Return:
https://SERVER/browse/PROJECTKEY

Expected Return:
https://SERVER/PATH/browse/PROJECTKEY

Same is true for 
````java
export const getIssueUrl = (issueUrl: string, issueKey: string) => {
  const url = new URL(issueUrl);
  return `https://${url.host}/browse/${issueKey}`;
};
````

### To reproduce

1. Set up JIRA Server with a BaseURL of https://SERVER/PATH
2. Install & Configure backstage 
3. install & Configure Plugin 
5. Open Backstage with plugin 

### Additional context

Found on JIRA Server

**Comment by anicke** [comment]
Yes, this should work! Thank you for the ticket, we will figure out a way to fix it.
