### ISSUE TITLE
Incorect dependency version in @axis-backstage/plugin-jira-dashboard 0.7.1

### ISSUE THREAD

**Issue by Antrakos** [AxisCommunications/backstage-plugins#93]
### Describe the bug

Newest 0.7.1 version of `@axis-backstage/plugin-jira-dashboard` was published with `workspace` version tag
```json
  "dependencies": {
    "@axis-backstage/plugin-jira-dashboard-common": "workspace:^",
```

This makes it impossible to yarn add it or yarn install it. I had to freeze it to 0.7.0 version to get it working
```shell
yarn --cwd packages/app add @axis-backstage/plugin-jira-dashboard

➤ YN0000: · Yarn 4.1.0
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: @axis-backstage/plugin-jira-dashboard-common@workspace:^: Workspace not found (@axis-backstage/plugin-jira-dashboard-common@workspace:^)
 
```

### To reproduce

Run `yarn --cwd packages/app add @axis-backstage/plugin-jira-dashboard` on any backstage project or add `"@axis-backstage/plugin-jira-dashboard": "0.7.1"` dependency to `packages/app/package.json` file and run `yarn install`.

### Screenshots

Here's package.json file of the released artifact: https://www.npmjs.com/package/@axis-backstage/plugin-jira-dashboard/v/0.7.1?activeTab=code

![image](https://github.com/AxisCommunications/backstage-plugins/assets/13787714/9f5ac813-ac94-4ecd-acc8-8ab862708d75)

### Additional context

My guess is that recent changes to publish process caused this issue by not resolving workspace version to a semver before releasing artifact.

**Comment by riginoommen** [comment]
I am also experiencing this issue
```
yarn workspace app add @axis-backstage/plugin-jira-dashboard            
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: @axis-backstage/plugin-jira-dashboard-common@workspace:^: Workspace not found (@axis-backstage/plugin-jira-dashboard-common@workspace:^)
    at Ye.getWorkspaceByDescriptor (/Users/roommen/.cache/node/corepack/yarn/3.7.0/yarn.js:440:3260)
    at gC.getCandidates (/Users/roommen/.cache/node/corepack/yarn/3.7.0/yarn.js:391:29582)
    at Rf.getCandidates (/Users/roommen/.cache/node/corepack/yarn/3.7.0/yarn.js:392:1264)
    at Rf.getCandidates (/Users/roommen/.cache/node/corepack/yarn/3.7.0/yarn.js:392:1264)
    at /Users/roommen/.cache/node/corepack/yarn/3.7.0/yarn.js:440:8033
    at Cf (/Users/roommen/.cache/node/corepack/yarn/3.7.0/yarn.js:391:11070)
    at ue (/Users/roommen/.cache/node/corepack/yarn/3.7.0/yarn.js:440:8013)
    at async Promise.allSettled (index 0)
    at async ro (/Users/roommen/.cache/node/corepack/yarn/3.7.0/yarn.js:391:10398)
➤ YN0000: └ Completed in 1s 851ms
➤ YN0000: Failed with errors in 1s 852ms
```

**Comment by GLundh** [comment]
Thanks for the issue. It should now be fixed. Please try latest version.
